name: Greeting from SHAN Yuzhen
on: push


jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Yuzhen
        MIDDLE_NAME: Alec
        LAST_NAME: SHAN
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
